---
k3os:
  password: '$1$XB4B4zRj$pOVU2/a/n.lSzkmvVoQDg0'
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/gCFT8TyDZKZLt1chusN7yStaiPSllLU2TT/qYX+q2r2JyOFVbKq6zh2kVvituAD4Q2zjy5QRMk7mQxuDu4IpTFpmLS1pdc8ZMhQ+vau27xRsn+8CRlcoPQhtqZrTqYnMqtp+HIzxTdZi/4TemyEe+BIG1Z0BWeCkqrjP3mNlQ2xDD6YADLAp/AvPGcTsR2ksZZOWa6De8Jd2uCVHGoXdUktY5SIn8fOZK4u5Xgn0vnBu8Ty5M577Qn1I+J3E/FwSzFhZGZGBCvvWShG7xlzTh5NNw+Ev4UpBd25y6sYmxa3lKKYs6iuGlV4JKv2cqQ5CI2ZFqTCR+Hti2xdi0HfxpLjyjqA3u7u6Qzb1kDDxKeJBNWTE8iq2gzER8PRG2X4mTi8Atz1ddNg9n59YoAiLP7+HOE5UhWmVvLPusN7OP922lEqMKGPkWIm1ukKagQJSmMUWEqf/ilWbcKCVH2sLh2LZXPK5pIeyGY+/yCM5Wr6jSgz64ddHlhBssaYhpEopUMse2dLNDToMtifpaMUcoTWRITQbEY/LJ2RjPrb7XPu/TV0Bhu7b4wCy1W1bMkQAVrNlVGNJDfLQqC94QsxUecv7vPlQhAOes8k6iL+K+Tx5PGFyDExck5o/D1TgOExWiIsqOrx1jsRVRQClwmC8cATlX3CF3/XqvKORpcVbEw==
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2TBZGjE+J8ag11dzkFT58J3XPONrDVmalCNrKxsfADfyy0eqdZrG8hcAxAR/5zuj90Gin2uBR4Sw6Cn4VHsPZcFpXyQCjK1QDADj+WcuhpXOIOY3AB0LZBly9NI0ll+8lo3QtEaoyRLtrMBhQ6Mooy2M3MTG4JNwU9o3yInuqZWf9PvtW6KxMl+ygg1xZkljhemGZ9k0wSrjqif+8usNbzVlCOVQmZwZA+BZxbdcLNwkg7zWJSXzDIXyqM6iWPGXQDEbWLq3+HR1qKucTCSxjbqoe0FD5xcW7NHIME5XKX84yH92n6yn+rxSsyUfhJWYqJd+i0fKf5UbN6qLrtd/D
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    echo hello, local service start
  owner: root
  path: /etc/local.d/example.start
  permissions: '0755'
